var toleranceList = [
    { name: 'POS销售价格（单价）', isSelect: false, code: 'ProdAMT' },
    { name: 'POS销售数量', isSelect: false, code: 'BaseQTY' },
    { name: 'POS销售金额（含税）', isSelect: false, code: 'POSSalesAmountTaxIncluded' },
    { name: 'POS销售金额（未税）', isSelect: false, code: 'POSSalesAmountTaxFress' },
    { name: 'POS销售金额（基价）', isSelect: false, code: 'PosSalesAmountBasePrice' },
    { name: 'POS销售单价（基价）', isSelect: false, code: 'GroupPrice' },
    { name: 'POS销售单价（RSP）', isSelect: false, code: 'RSPPrice' },
    { name: 'POS销售金额（RSP）', isSelect: false, code: 'PosSalesAmountRSP' },
    { name: '开始时间', code: 'StartTime' },
    { name: '结束时间', code: 'EndTime' } 
]

var siftList = [
    // {name: '大区', isSelect: false, code: 'AreaName', placeholder: '请选择大区', type: 'select', list: []},
    // {name: '省份', isSelect: false, code: 'ProvinceName', placeholder: '请选择省份', type: 'select', list: []},
    // {name: '城市', isSelect: false, code: 'CityName', placeholder: '请选择城市', type: 'select', list: []},
    // {name: '门店编号', isSelect: false, code: 'StoreCode', placeholder: '请输入门店编号', type: 'input'},
    // {name: '门店名称', isSelect: false, code: 'StoreName', placeholder: '请输入门店名称', type: 'input'},
    // {name: '大区', isSelect: false, code: 'AreaName', placeholder: '请选择大区', type: 'select', list: []},
    // {name: '省份', isSelect: false, code: 'ProvinceName', placeholder: '请选择省份', type: 'select', list: []},
    // {name: '城市', isSelect: false, code: 'CityName', placeholder: '请选择城市', type: 'select', list: []},
    // {name: '县级市', isSelect: false, code: 'CountyLevelCity', placeholder: '请选择城市', type: 'select', list: []},
]

var siftAllList = [
    { name: '大区', isSelect: false, code: 'AreaName', placeholder: '请选择大区', type: 'select', list: [] },
    { name: '省份', isSelect: false, code: 'ProvinceName', placeholder: '请选择省份', type: 'select', list: [] },
    { name: '城市', isSelect: false, code: 'CityName', placeholder: '请选择城市', type: 'select', list: [] },
    { name: '县级市', isSelect: false, code: 'CountyLevelCity', placeholder: '请选择城市', type: 'select', list: [] },
    { name: '门店类型', isSelect: false, code: 'StoreTypeCode', placeholder: '请选择门店类型', type: 'select', list: [] },
    { name: '门店类型细分', isSelect: false, code: 'SubStoreTypeCode', placeholder: '请选择门店类型细分', type: 'select', list: [] },
    { name: '门店定义', isSelect: false, code: 'StoreDefineCode', placeholder: '请选择门店类型', type: 'select', list: [] },
    { name: '供货形式', isSelect: false, code: 'SupplyFormCode', placeholder: '请选择门店类型', type: 'select', list: [] },
    // {name: '经销商编码', isSelect: false, code: 'DistributorNo', placeholder: '请输入经销商编码', type: 'input'},
    // {name: '经销商名称', isSelect: false, code: 'DistributorName', placeholder: '请输入经销商名称', type: 'input'},
    // {name: '经销商处客户编码', isSelect: false, code: 'DIST_STORE_CODE', placeholder: '请输入门店编号', type: 'input'},
    // {name: '经销商处客户名称', isSelect: false, code: 'DIST_STORE_NAME', placeholder: '请输入门店名称', type: 'input'},
    { name: '门店编号', isSelect: false, code: 'StoreCode', placeholder: '请输入门店编号', type: 'input' },
    { name: '门店名称', isSelect: false, code: 'StoreName', placeholder: '请输入门店名称', type: 'input' },

    // {name: '门店地址', isSelect: false, code: 'StoreLocation', placeholder: '请输入门店地址', type: 'input'},
    { name: '品类', isSelect: false, code: 'Category', placeholder: '请选择品类', type: 'select', list: [] },
    { name: '子品类', isSelect: false, code: 'SubCategory', placeholder: '请选择子品类', type: 'select', list: [] },
    { name: '品牌', isSelect: false, code: 'Brand', placeholder: '请选择品牌', type: 'select', list: [] },
    { name: '产品线', isSelect: false, code: 'ProductLine', placeholder: '请选择产品线', type: 'select', list: [] },
    { name: '产品组', isSelect: false, code: 'ProductGroup', placeholder: '请选择产品组', type: 'select', list: [] },
    { name: '产品规格', isSelect: false, code: 'ProductSpecification', placeholder: '请输入产品规格', type: 'input' },
    { name: '标准产品名称', isSelect: false, code: 'ProductName', placeholder: '请输入标准产品名称', type: 'input' },
    { name: '标准产品编码', isSelect: false, code: 'ProductCode', placeholder: '请输入标准产品编码', type: 'input' },
    { name: '标准产品条形码', isSelect: false, code: 'ProductBarCode', placeholder: '请输入标准产品条形码', type: 'input' },
    { name: '经销商产品名称', isSelect: false, code: 'DistProdName', placeholder: '请输入经销商产品名称', type: 'input' },
    { name: '经销商产品编码', isSelect: false, code: 'DistProdCode', placeholder: '请输入经销商产品编码', type: 'input' },
    { name: '经销商产品条形码', isSelect: false, code: 'DistProdBarCode', placeholder: '请输入经销商产品条形码', type: 'input' },
    { name: '经销商', isSelect: false, code: 'DistributorName', placeholder: '请选择经销商', type: 'select', list: [] },
    { name: '经销商编码', isSelect: false, code: 'DistributorNo', placeholder: '请选择经销商编码', type: 'select', list: [] },
    { name: '经销商处客户编码', isSelect: false, code: 'DistCustomerCode', placeholder: '请选择经销商处客户编码', type: 'input' },
    { name: '经销商处客户名称', isSelect: false, code: 'DistCustomerName', placeholder: '请选择经销商处客户名称', type: 'input' },
    { name: 'KA编码', isSelect: false, code: 'DistCode', placeholder: '请选择KA编码', type: 'input' },
    { name: 'KA名称', isSelect: false, code: 'DistName', placeholder: '请选择KA名称', type: 'input' },
] 
